// import type { Metadata } from "next";
// import { Inter,Poppins } from "next/font/google"; // 661 (gzipped :386)
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// const poppins = Poppins({
//   subsets:['latin'],
//   variable: '--font-poppins',
//   weight:['100','200','300','400','500','600','700','800','900'],
// });

// export const metadata: Metadata = {
//   title: "snippet",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={poppins.className}>{children}</body>
//     </html>
//   );
// }

// //src/app/layout.tsx
 

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "snippet",
  description: "Radcom application",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider> 
      <body className={inter.className}>
          <>{children}</>
      </body>
      </ClerkProvider>
    </html>
  );
}

